"""Añade términos de glosario por tema a data/temaNN-visual.json (idempotente por id)."""
import json,sys
A={
1:[
("derechos-deberes","Derechos y deberes fundamentales","Los derechos básicos de las personas (vida, libertad, igualdad, educación…) y las obligaciones básicas (defender España, pagar impuestos). Están en el Título I de la Constitución.","CE, Título I"),
("recurso-amparo","Recurso de amparo","Reclamación ante el Tribunal Constitucional de una persona cuyos derechos fundamentales (arts. 14 a 29 y objeción de conciencia) han sido vulnerados, cuando ya no cabe otra vía.","Art. 53.2 CE"),
("habeas-corpus","Habeas corpus","Procedimiento rápido para que un juez compruebe si una detención es legal y ponga en libertad a la persona si no lo es.","Art. 17.4 CE"),
("defensor-pueblo","Defensor del Pueblo","Alto comisionado de las Cortes Generales que defiende los derechos del Título I vigilando a la Administración.","Art. 54 CE"),
("estados-excepcionales","Estados de alarma, excepción y sitio","Situaciones de crisis grave en las que se pueden limitar derechos. Los declara el Gobierno (alarma) o el Congreso (excepción y sitio).","Art. 116 CE"),
("reforma-constitucional","Reforma constitucional","Cambio de la Constitución. Hay un procedimiento ordinario (art. 167) y otro agravado para las partes más protegidas (art. 168).","Arts. 166 a 169 CE"),
("cuestion-confianza","Cuestión de confianza","El Presidente del Gobierno pide al Congreso que respalde su programa o una declaración de política general.","Art. 112 CE"),
("mocion-censura","Moción de censura","Forma de sustituir al Presidente del Gobierno: el Congreso, por mayoría absoluta, elige a otro candidato.","Art. 113 CE"),
("inviolabilidad-rey","Inviolabilidad del Rey","La persona del Rey no está sujeta a responsabilidad; sus actos siempre necesitan refrendo.","Art. 56.3 CE"),
("tribunal-cuentas","Tribunal de Cuentas","Órgano que controla las cuentas y la gestión económica del Estado y del sector público.","Art. 136 CE"),
],
2:[
("discriminacion-directa","Discriminación directa por razón de sexo","Tratar a una persona peor que a otra en situación comparable por su sexo.","Art. 6.1 LO 3/2007"),
("acoso-por-razon-sexo","Acoso por razón de sexo","Comportamiento basado en el sexo de la persona que atenta contra su dignidad y crea un entorno intimidatorio, degradante u ofensivo.","Art. 7.2 LO 3/2007"),
("carga-prueba","Carga de la prueba","Quién debe demostrar algo. En discriminación por sexo, si la persona demandante da indicios, debe probar la parte demandada que no hubo discriminación.","Art. 13 LO 3/2007"),
("presencia-equilibrada","Presencia equilibrada","Que ni mujeres ni hombres superen el 60 % ni bajen del 40 % en un órgano o conjunto de personas.","Disp. adic. 1.ª LO 3/2007"),
("plan-igualdad","Plan de igualdad","Conjunto de medidas para lograr la igualdad de trato y oportunidades y eliminar la discriminación por razón de sexo en una organización.","Arts. 45 y 46 LO 3/2007"),
("violencia-contra-mujeres","Violencia contra las mujeres (Aragón)","Todo acto o agresión motivado por pertenecer al sexo femenino que cause o pueda causar daño físico o psicológico.","Art. 1.2 Ley 4/2007 Aragón"),
("casa-acogida","Casa de acogida","Servicio de alojamiento temporal para mujeres víctimas de violencia y sus hijos que han dejado su domicilio.","Ley 4/2007 Aragón"),
("instituto-aragones-mujer","Instituto Aragonés de la Mujer","Organismo autonómico que impulsa la igualdad y presta servicios a las víctimas de violencia.","Ley 4/2007 Aragón"),
],
3:[
("estatuto-aragon","Estatuto de Autonomía de Aragón","Norma básica de la Comunidad: dice cuáles son sus instituciones, derechos y competencias. Es una ley orgánica.","LO 5/2007"),
("diputacion-permanente","Diputación Permanente","Órgano que vela por los poderes de las Cortes de Aragón cuando no están reunidas o han sido disueltas.","Estatuto de Aragón"),
("decreto-ley-aragon","Decreto-ley de Aragón","Norma con rango de ley que dicta el Gobierno de Aragón en caso de necesidad urgente; las Cortes deben convalidarla en 30 días.","Art. 44 EAAr"),
("derecho-foral","Derecho foral aragonés","Derecho civil propio de Aragón, que se aplica a quienes tienen vecindad civil aragonesa.","Arts. 9.2 y 71 EAAr"),
("comarca","Comarca","Entidad local formada por municipios limítrofes con intereses comunes, importante para vertebrar el territorio aragonés.","Art. 83 EAAr"),
("consejo-consultivo-aragon","Consejo Consultivo de Aragón","Supremo órgano consultivo del Gobierno y la Administración de la Comunidad Autónoma.","Art. 58 EAAr"),
("clausula-subrogatoria","Cláusula subrogatoria","Aragón ejerce las funciones que la ley atribuya al Gobierno del Estado respecto a la Administración de Justicia en su territorio.","Art. 69 EAAr"),
("cuestion-confianza-aragon","Cuestión de confianza en Aragón","El Presidente de Aragón pide a las Cortes que respalden su programa; se entiende otorgada con mayoría simple.","Art. 49 EAAr"),
],
4:[
("capacidad-juridica","Capacidad jurídica","Aptitud para ser titular de derechos y obligaciones. Todas las personas la tienen.","Código Civil"),
("legitimacion-interesado","Legitimación","Relación de una persona con un asunto que le permite actuar en el procedimiento como interesada.","Art. 4 Ley 39/2015"),
("representacion","Representación","Actuar en nombre de otra persona. Se puede acreditar por escrito, por comparecencia o con apoderamiento apud acta.","Art. 5 Ley 39/2015"),
("registro-electronico-apoderamientos","Registro electrónico de apoderamientos","Registro donde se inscriben los poderes para actuar en nombre de otra persona ante la Administración.","Art. 6 Ley 39/2015"),
("identificacion-firma","Identificación y firma","Identificarse prueba quién eres; firmar prueba que expresas tu voluntad y consientes un contenido.","Arts. 9 y 10 Ley 39/2015"),
("persona-obligada-electronico","Obligados a relacionarse electrónicamente","Personas jurídicas, entidades sin personalidad, profesionales con colegiación obligatoria, empleados públicos y quienes representen a obligados.","Art. 14.2 Ley 39/2015"),
("clave","Cl@ve","Sistema de identificación electrónica común de las Administraciones, que permite acceder a trámites con usuario y contraseña o certificado.","Ley 39/2015"),
],
5:[
("lenguas-cooficiales","Lenguas cooficiales","Idiomas oficiales de una Comunidad junto al castellano. Los interesados pueden usarlas ante la Administración de su territorio.","Art. 15 Ley 39/2015"),
("computo-plazos","Cómputo de plazos","Cómo se cuentan los plazos: por días son hábiles, y empiezan al día siguiente de la notificación o publicación.","Art. 30 Ley 39/2015"),
("ampliacion-plazos","Ampliación de plazos","Prolongar un plazo hasta la mitad cuando las circunstancias lo aconsejan y no se perjudican derechos de terceros.","Art. 32 Ley 39/2015"),
("tramitacion-urgencia","Tramitación de urgencia","Reduce a la mitad los plazos del procedimiento, salvo los de presentar solicitudes y recursos.","Art. 33 Ley 39/2015"),
("comunicacion-previa","Comunicación previa","Documento por el que se informa a la Administración de datos para iniciar una actividad; permite empezar desde su presentación.","Art. 69 Ley 39/2015"),
("copia-autentica","Copia auténtica","Copia de un documento con el mismo valor que el original, hecha por la Administración.","Art. 27 Ley 39/2015"),
("registro-general","Registro general","Lugar donde se anotan las entradas y salidas de documentos para dejar constancia de cuándo se presentaron.","Art. 16 Ley 39/2015"),
],
6:[
("eficacia-acto","Eficacia de los actos","Los actos producen efectos desde que se dictan, salvo que necesiten notificación, publicación o aprobación superior.","Art. 39 Ley 39/2015"),
("ejecutividad","Ejecutividad","Los actos administrativos se pueden cumplir y exigir desde que son eficaces, aunque se recurran, salvo suspensión.","Art. 98 Ley 39/2015"),
("retroactividad-acto","Retroactividad de los actos","Excepcionalmente un acto puede surtir efectos desde una fecha anterior si es favorable y los supuestos ya existían.","Art. 39.3 Ley 39/2015"),
("nulidad-pleno-derecho","Nulidad de pleno derecho","Defecto muy grave del acto (por ejemplo, lesionar derechos fundamentales o dictarlo un órgano manifiestamente incompetente).","Art. 47 Ley 39/2015"),
("conservacion-actos","Conservación de actos","Si se anula una parte del acto, el resto se mantiene si es independiente de la parte anulada.","Art. 49 Ley 39/2015"),
("forma-actos","Forma de los actos","Los actos se producen por escrito a través de medios electrónicos, salvo que la naturaleza exija otra forma.","Art. 36 Ley 39/2015"),
("publicacion-sustitutoria","Publicación","Cuando no se puede notificar o los interesados son indeterminados, se publica en el BOE o en el diario oficial correspondiente.","Art. 44 y 45 Ley 39/2015"),
],
7:[
("iniciacion-oficio","Iniciación de oficio","El procedimiento lo inicia la propia Administración por acuerdo del órgano competente.","Art. 58 Ley 39/2015"),
("iniciacion-solicitud","Iniciación a solicitud","El procedimiento lo inicia el interesado presentando una solicitud.","Art. 66 Ley 39/2015"),
("medidas-provisionales","Medidas provisionales","Medidas que adopta la Administración para asegurar la eficacia de la resolución final antes de que se dicte.","Art. 56 Ley 39/2015"),
("informacion-publica","Información pública","Trámite en que se abre el expediente al público para que cualquier persona pueda alegar. Dura al menos 20 días.","Art. 83 Ley 39/2015"),
("terminacion-convencional","Terminación convencional","El procedimiento acaba con un acuerdo entre la Administración y los interesados.","Art. 86 Ley 39/2015"),
("pruebas","Prueba","Actuaciones para acreditar los hechos del procedimiento. Se pueden practicar en un plazo de 10 a 30 días.","Art. 77 Ley 39/2015"),
("renuncia-derecho","Renuncia","El interesado abandona su derecho. Pone fin al procedimiento si no está prohibida por el ordenamiento.","Art. 94 Ley 39/2015"),
("procedimiento-simplificado","Procedimiento simplificado","Procedimiento acortado (30 días) para casos de especial sencillez o sin complejidad.","Art. 96 Ley 39/2015"),
],
8:[
("revocacion-actos","Revocación","La Administración retira un acto de gravamen o desfavorable por motivos de oportunidad o legalidad, sin ir contra la ley.","Art. 109 Ley 39/2015"),
("rectificacion-errores","Rectificación de errores","Corrección de errores materiales, de hecho o aritméticos en un acto, en cualquier momento.","Art. 109.2 Ley 39/2015"),
("recurso-extraordinario-revision","Recurso extraordinario de revisión","Recurso excepcional contra actos firmes, solo por causas tasadas (error de hecho, documentos nuevos, falsedad, etc.).","Art. 125 Ley 39/2015"),
("acto-firme","Acto firme","Acto que ya no admite recurso porque ha pasado el plazo o se han agotado las vías.","Ley 39/2015"),
("plazo-recurso-alzada","Plazo del recurso de alzada","Un mes si el acto es expreso; tres meses si no lo es (silencio).","Art. 122 Ley 39/2015"),
("suspension-ejecucion","Suspensión de la ejecución","Paralizar temporalmente el cumplimiento del acto recurrido cuando puede causar perjuicios de imposible reparación o es nulo.","Art. 117 Ley 39/2015"),
("recurso-potestativo-reposicion","Recurso potestativo de reposición","Recurso que se interpone ante el mismo órgano que dictó el acto, en el plazo de un mes. Es opcional.","Art. 123 Ley 39/2015"),
],
9:[
("contrato-obras","Contrato de obras","El que tiene por objeto realizar una obra o ejecutar trabajos de construcción o ingeniería civil.","Art. 13 LCSP"),
("contrato-suministro","Contrato de suministro","El que tiene por objeto adquirir, arrendar o comprar productos o bienes muebles.","Art. 16 LCSP"),
("contrato-servicios","Contrato de servicios","El que tiene por objeto prestaciones de hacer consistentes en una actividad o un resultado distinto de una obra o suministro.","Art. 17 LCSP"),
("poder-adjudicador","Poder adjudicador","Entidad del sector público que puede adjudicar contratos: Administraciones Públicas y otros entes.","Art. 3 LCSP"),
("pliego-clausulas","Pliego de cláusulas administrativas","Documento con las condiciones jurídicas, económicas y administrativas que regirán el contrato.","Art. 122 LCSP"),
("pliego-prescripciones","Pliego de prescripciones técnicas","Documento con las características técnicas de lo que se va a contratar.","Art. 124 LCSP"),
("procedimiento-abierto","Procedimiento abierto","Cualquier empresa interesada puede presentar una oferta.","Art. 156 LCSP"),
("clasificacion-empresas","Clasificación de empresas","Acreditación oficial de la solvencia de una empresa para contratar determinados tipos de contrato.","Art. 77 LCSP"),
("garantia-definitiva","Garantía definitiva","Fianza que presta el adjudicatario, un 5 % del precio de adjudicación sin IVA, para responder del contrato.","Art. 107 LCSP"),
("prohibicion-contratar","Prohibición de contratar","Impedimento para contratar con el sector público por haber cometido ciertas infracciones.","Art. 71 LCSP"),
],
10:[
("bienes-uso-publico","Bienes de uso público","Bienes demaniales que usa directamente la ciudadanía: calles, plazas, parques, caminos.","Art. 3 RBASO"),
("servicio-publico-bien","Bienes de servicio público","Bienes destinados directamente a un servicio público local, como el edificio del Ayuntamiento o un colegio público.","Art. 3 RBASO"),
("inalienable","Inalienable, imprescriptible e inembargable","Características de los bienes de dominio público: no se pueden vender, no se ganan por el paso del tiempo y no se pueden embargar.","Art. 132 CE"),
("mutacion-demanial","Mutación demanial","Cambio de destino de un bien de dominio público a otro uso público sin que pierda su carácter.","RBASO"),
("adscripcion","Adscripción","Destinar un bien de una Administración a un órgano o servicio que lo va a utilizar.","Legislación patrimonial"),
("usucapion","Prescripción adquisitiva","Ganar la propiedad de un bien por poseerlo durante cierto tiempo. No se puede hacer con bienes demaniales.","Código Civil"),
("recuperacion-oficio","Recuperación de oficio","Facultad de la entidad local de recobrar por sí misma la posesión de sus bienes indebidamente ocupados.","Art. 82 LBRL"),
("deslinde","Deslinde","Procedimiento para determinar los límites de un bien de la entidad local.","Art. 56 RBASO"),
("patrimonio-municipal-suelo","Patrimonio municipal del suelo","Conjunto de bienes de la entidad local destinados a fines sociales y de vivienda protegida.","Legislación urbanística"),
],
11:[
("servicio-publico","Servicio público","Actividad de titularidad pública que satisface necesidades de la ciudadanía.","Art. 85 LBRL"),
("servicios-obligatorios","Servicios mínimos obligatorios","Servicios que todos los municipios deben prestar (alumbrado, cementerio, recogida de residuos…), con más según población.","Art. 26 LBRL"),
("reserva-servicios","Reserva de servicios","Servicios esenciales que la ley reserva a las entidades locales, como el abastecimiento domiciliario de agua o la recogida de residuos.","Art. 86 LBRL"),
("orden-ejecucion","Orden de ejecución","Mandato del Ayuntamiento para que el propietario realice obras de conservación o seguridad.","Legislación urbanística"),
("licencia-actividad","Licencia de actividad","Autorización para abrir una actividad económica en un local una vez comprobado que cumple la normativa.","Art. 84 LBRL"),
("entidad-publica-empresarial","Entidad pública empresarial","Entidad pública que presta servicios o produce bienes a cambio de un precio, con formas empresariales.","Art. 85 bis LBRL"),
("sociedad-mercantil-local","Sociedad mercantil local","Empresa cuyo capital pertenece íntegramente a la entidad local, para gestionar un servicio de forma directa.","Art. 85.2 LBRL"),
("consorcio","Consorcio","Entidad formada por varias Administraciones para gestionar juntas un servicio de interés común.","Ley 40/2015"),
],
12:[
("recursos-haciendas","Recursos de las haciendas locales","Fuentes de ingresos de las entidades locales: tributos, participación en los del Estado y Comunidad, ingresos patrimoniales y operaciones de crédito.","Art. 2 TRLRHL"),
("tasa-concepto","Tasa","Tributo que se paga por usar el dominio público o recibir un servicio que beneficia al obligado y que no se presta por el sector privado.","Art. 20 TRLRHL"),
("precio-publico-local","Precio público local","Contraprestación por servicios que sí pueden prestar los particulares o que se solicitan voluntariamente.","Art. 41 TRLRHL"),
("ibi","Impuesto sobre Bienes Inmuebles","Impuesto municipal obligatorio que grava la titularidad de bienes inmuebles.","Art. 60 TRLRHL"),
("iae","Impuesto sobre Actividades Económicas","Impuesto municipal obligatorio que grava el ejercicio de actividades económicas.","Art. 78 TRLRHL"),
("ivtm","Impuesto sobre Vehículos de Tracción Mecánica","Impuesto municipal obligatorio que grava la titularidad de vehículos aptos para circular.","Art. 92 TRLRHL"),
("icio","Impuesto sobre Construcciones, Instalaciones y Obras","Impuesto municipal potestativo que grava la realización de obras para las que se exige licencia.","Art. 100 TRLRHL"),
("iivtnu","Impuesto sobre el Incremento de Valor de los Terrenos","Impuesto municipal potestativo (plusvalía) sobre el aumento de valor de terrenos urbanos al transmitirlos.","Art. 104 TRLRHL"),
("participacion-tributos","Participación en tributos del Estado","Parte de la recaudación estatal que se reparte entre los municipios para financiarlos.","Art. 39 TRLRHL"),
("imposicion-ordenacion","Imposición y ordenación","El Ayuntamiento acuerda crear un tributo (imposición) y regula sus elementos mediante ordenanza fiscal (ordenación).","Art. 15 TRLRHL"),
("exencion-bonificacion","Exención y bonificación","La exención libra totalmente de pagar el tributo; la bonificación solo reduce la cuota.","TRLRHL"),
],
13:[
("estabilidad-presupuestaria","Estabilidad presupuestaria","Situación de equilibrio o superávit estructural de las cuentas públicas.","LO 2/2012"),
("estado-ingresos-gastos","Estado de gastos e ingresos","Partes del presupuesto: el estado de gastos recoge los créditos que se pueden gastar y el de ingresos lo que se prevé recaudar.","Art. 165 TRLRHL"),
("ejercicio-presupuestario","Ejercicio presupuestario","Periodo de vigencia del presupuesto, que coincide con el año natural.","Art. 163 TRLRHL"),
("modificacion-credito","Modificación de crédito","Cambio en los créditos aprobados: crédito extraordinario, suplemento, ampliación, transferencia, generación o incorporación.","Arts. 177 a 182 TRLRHL"),
("credito-extraordinario","Crédito extraordinario","Crédito para un gasto que no puede esperar al ejercicio siguiente y para el que no hay crédito.","Art. 177 TRLRHL"),
("liquidacion-presupuesto","Liquidación del presupuesto","Cierre de las cuentas del ejercicio: obligaciones reconocidas, derechos reconocidos y remanente de tesorería.","Art. 191 TRLRHL"),
("cuenta-general","Cuenta general","Conjunto de cuentas de la entidad local que se rinde al Tribunal de Cuentas.","Art. 208 TRLRHL"),
("interventor","Interventor","Funcionario de habilitación nacional que fiscaliza la gestión económica y presupuestaria.","Art. 213 TRLRHL"),
("tesoreria","Tesorería","Conjunto de recursos financieros líquidos de la entidad local (dinero, valores y créditos).","Art. 194 TRLRHL"),
("ordenacion-pago","Ordenación del pago","Acto por el que el ordenador de pagos ordena que se pague una obligación reconocida.","Art. 187 TRLRHL"),
],
14:[
("elementos-municipio","Elementos del municipio","Territorio, población y organización.","Art. 11 LBRL"),
("termino-municipal","Término municipal","Territorio donde el Ayuntamiento ejerce sus competencias.","Art. 12 LBRL"),
("vecino","Vecino","Persona residente que está inscrita en el padrón municipal del municipio donde vive habitualmente.","Art. 15 LBRL"),
("competencia-propia","Competencia propia","Competencia que el municipio ejerce en nombre propio, con autonomía, y que solo puede atribuir una ley.","Art. 7 LBRL"),
("competencia-delegada","Competencia delegada","Competencia de otra Administración que el municipio ejerce por delegación, bajo su control.","Art. 27 LBRL"),
("pleno-municipal","Pleno","Órgano formado por todos los concejales y presidido por el Alcalde; toma las decisiones más importantes.","Art. 22 LBRL"),
("alcalde","Alcalde","Presidente de la corporación; dirige el gobierno y la administración municipal y es elegido por los concejales o por los vecinos.","Art. 21 LBRL"),
("comisiones-informativas","Comisiones informativas","Órganos de estudio de los asuntos que va a tratar el Pleno, sin capacidad de decidir.","Art. 20 LBRL"),
("regimen-especial","Régimen especial","Régimen distinto del común por razones singulares, como el concejo abierto o el de gran población.","Arts. 29 y 121 LBRL"),
("convenio-colaboracion","Convenios de colaboración","Acuerdos entre Administraciones para ejercer juntas competencias o prestar servicios.","Ley 40/2015"),
],
15:[
("entidad-local-menor","Entidad local de ámbito inferior al municipio","Entidad con personalidad propia dentro de un municipio (pedanía, barrio, anejo), con órganos propios.","Art. 45 LBRL"),
("participacion-ciudadana","Participación ciudadana","Derecho de los vecinos a intervenir en los asuntos públicos locales mediante información, consulta, iniciativa o audiencia.","Arts. 69 y 70 bis LBRL"),
("consulta-popular","Consulta popular","Consulta a los vecinos sobre asuntos de competencia propia municipal, que requiere autorización del Estado.","Art. 71 LBRL"),
("derecho-peticion","Derecho de petición","Derecho de toda persona a dirigir peticiones a la Administración, sin que se estime obligatoria su concesión.","Art. 29 CE"),
("audiencia-publica","Audiencia pública","Sesión o trámite abierto a la ciudadanía y asociaciones para opinar sobre decisiones municipales.","ROT"),
("asociaciones-vecinales","Asociaciones vecinales","Entidades ciudadanas que defienden los intereses generales o sectoriales de los vecinos.","Art. 72 LBRL"),
("consejo-sectorial","Consejo sectorial","Órgano de participación sobre un ámbito concreto (mayores, juventud, medio ambiente…).","ROT"),
("junta-distrito","Junta de distrito","Órgano territorial de gestión desconcentrada de un municipio de gran población.","Art. 128 LBRL"),
],
16:[
("potestad-normativa","Potestad normativa","Poder de dictar normas jurídicas generales. El municipio tiene potestad reglamentaria pero no legislativa.","Art. 4 LBRL"),
("procedimiento-ordenanzas","Procedimiento de aprobación de ordenanzas","Aprobación inicial por el Pleno, información pública y audiencia por 30 días como mínimo, y aprobación definitiva.","Art. 49 LBRL"),
("entrada-vigor","Entrada en vigor","Momento desde el que obliga una norma: se publica su texto íntegro y transcurre el plazo del art. 65.2 LBRL.","Art. 70.2 LBRL"),
("jerarquia-local","Jerarquía de las normas locales","Los reglamentos y disposiciones administrativas no pueden vulnerar la Constitución ni las leyes ni regular materias reservadas a la ley.","Art. 128 Ley 39/2015"),
("reglamento-organico","Reglamento orgánico","Reglamento que regula la organización y funcionamiento de los órganos municipales.","Art. 20 LBRL"),
("consulta-previa","Consulta pública previa","Trámite anterior a elaborar una norma en el que se recoge la opinión de ciudadanos y organizaciones sobre el problema, la necesidad y los objetivos.","Art. 133 Ley 39/2015"),
("bando-alcaldia","Bando","Disposición del Alcalde para recordar o aplicar normas ya existentes; no crea derecho nuevo.","Art. 21.1 e) LBRL"),
("reserva-ley","Reserva de ley","Materias que solo pueden regularse por ley y no por reglamento.","Art. 53.1 CE"),
],
17:[
("funcionario-carrera-def","Funcionario de carrera","Persona nombrada legalmente que mantiene una relación estatutaria permanente con la Administración.","Art. 9 TREBEP"),
("personal-laboral","Personal laboral","Empleados con contrato de trabajo, fijos o temporales.","Art. 11 TREBEP"),
("personal-directivo","Personal directivo profesional","Quienes desempeñan funciones directivas profesionales en las Administraciones.","Art. 13 TREBEP"),
("derechos-individuales","Derechos individuales","Derechos del empleado público como inamovilidad, carrera profesional, retribuciones, vacaciones y permisos.","Art. 14 TREBEP"),
("derechos-colectivos","Derechos colectivos","Derechos como la libertad sindical, la negociación colectiva y el planteamiento de conflictos colectivos.","Art. 15 TREBEP"),
("deberes-empleado","Deberes de los empleados públicos","Principios éticos y de conducta: objetividad, integridad, neutralidad, responsabilidad, imparcialidad.","Arts. 52 a 54 TREBEP"),
("codigo-conducta","Código de conducta","Principios éticos y de conducta que deben respetar los empleados públicos.","Arts. 52 a 54 TREBEP"),
("cuerpos-escalas","Cuerpos y escalas","Agrupaciones de funcionarios con titulación y funciones similares.","Art. 75 TREBEP"),
("grupos-clasificacion","Grupos de clasificación","Los funcionarios se agrupan según su titulación: A (subgrupos A1 y A2), B y C (C1 y C2).","Art. 76 TREBEP"),
("negociacion-colectiva","Negociación colectiva","Derecho a negociar las condiciones de trabajo entre representantes de la Administración y sindicatos.","Art. 31 TREBEP"),
],
18:[
("oferta-empleo","Oferta de empleo público","Plazas vacantes que la Administración decide cubrir en un año, aprobada por el órgano competente.","Art. 70 TREBEP"),
("proceso-selectivo","Proceso selectivo","Procedimiento para elegir a los empleados públicos: oposición, concurso-oposición o, excepcionalmente, concurso.","Art. 61 TREBEP"),
("oposicion","Oposición","Sistema selectivo basado en pruebas de conocimientos y capacidades.","Art. 61 TREBEP"),
("concurso","Concurso","Sistema selectivo basado en la valoración de méritos.","Art. 61 TREBEP"),
("provision-puestos","Provisión de puestos","Forma de cubrir un puesto concreto: concurso o libre designación con convocatoria pública.","Art. 78 TREBEP"),
("servicio-activo","Servicio activo","Situación del funcionario que presta servicios en su puesto.","Art. 87 TREBEP"),
("servicios-especiales","Servicios especiales","Situación del funcionario que ejerce un cargo público o misión específica, con reserva de plaza y cómputo de antigüedad.","Art. 87 TREBEP"),
("suspension-funciones","Suspensión de funciones","Situación en que el funcionario queda privado de sus funciones y derechos durante el tiempo que dure la suspensión.","Art. 90 TREBEP"),
("separacion-servicio","Separación del servicio","Sanción por falta muy grave que hace perder la condición de funcionario.","Art. 96 TREBEP"),
("incompatibilidades","Incompatibilidades","Prohibición de compatibilizar el puesto público con otros trabajos o actividades que afecten a su imparcialidad.","Ley 53/1984"),
("jubilacion","Jubilación","Pérdida de la condición de funcionario por cumplir la edad legal (jubilación forzosa a los 65 años).","Art. 67 TREBEP"),
],
19:[
("funcion-publica-local","Función pública local","Régimen de los empleados de las entidades locales, regido por la legislación básica y la autonómica.","Arts. 91 a 94 LBRL"),
("funcionarios-habilitacion","Funcionarios con habilitación de carácter nacional","Funcionarios locales para funciones de secretaría, intervención-tesorería, reservadas por el Estado.","Art. 92 bis LBRL"),
("secretaria-intervencion","Secretaría-intervención","Subescala que ejerce funciones de secretaría e intervención en municipios pequeños.","RD 128/2018"),
("relacion-puestos","Relación de puestos de trabajo","Instrumento que ordena los puestos de la Administración: denominación, funciones, requisitos y retribuciones.","Art. 74 TREBEP"),
("retribuciones-basicas","Retribuciones básicas","Sueldo, trienios y pagas extraordinarias.","Art. 23 TREBEP"),
("retribuciones-complementarias","Retribuciones complementarias","Complemento de destino, específico, de productividad y gratificaciones.","Art. 24 TREBEP"),
("trienio","Trienio","Retribución que se cobra por cada tres años de servicio.","Art. 23 TREBEP"),
("personal-eventual-local","Personal eventual","Personal de confianza o asesoramiento especial, cuyo nombramiento y cese son libres.","Art. 104 bis LBRL"),
("escala-administracion-general","Escala de Administración general","Escala con funciones administrativas comunes, que incluye las subescalas técnica, de gestión, administrativa y auxiliar.","Art. 167 TRRL"),
],
20:[
("clasificacion-suelo","Clasificación del suelo","División del territorio en suelo urbano, urbanizable y no urbanizable, hecha por el plan general.","Art. 11 Ley de Urbanismo de Aragón"),
("suelo-urbano-consolidado","Suelo urbano consolidado","Suelo urbano que ya cuenta con todos los servicios y condición de solar.","Art. 13 Ley de Urbanismo de Aragón"),
("suelo-urbano-no-consolidado","Suelo urbano no consolidado","Suelo urbano que necesita completar su urbanización o hacerlo mediante reparcelación.","Art. 13 Ley de Urbanismo de Aragón"),
("solar","Solar","Superficie de suelo urbano apta para su uso inmediato porque cuenta con acceso, agua, saneamiento y energía.","Art. 14 Ley de Urbanismo de Aragón"),
("sector","Sector","Ámbito de suelo urbanizable o urbano no consolidado que se ordena con un plan parcial.","LUA"),
("aprovechamiento","Aprovechamiento","Edificabilidad que se puede materializar en un suelo. El propietario tiene derecho a una parte (aprovechamiento subjetivo).","Ley de Urbanismo de Aragón"),
("cesion-obligatoria","Cesión obligatoria","Suelo que el propietario entrega gratuitamente al municipio para viales, zonas verdes o equipamientos.","Ley de Urbanismo de Aragón"),
("proyecto-urbanizacion","Proyecto de urbanización","Proyecto técnico que define las obras de urbanización de un ámbito: calles, redes, jardines.","Ley de Urbanismo de Aragón"),
("deber-conservacion","Deber de conservación","Obligación del propietario de mantener edificios y terrenos en condiciones de seguridad y ornato.","Ley de Urbanismo de Aragón"),
("declaracion-ruina","Declaración de ruina","Declaración municipal de que un edificio no se puede reparar razonablemente y debe demolerse o desalojarse.","Art. 261 Ley de Urbanismo de Aragón"),
("disciplina-urbanistica","Disciplina urbanística","Conjunto de medidas para que se cumpla la ordenación urbanística: inspección, órdenes de restablecimiento y sanciones.","Arts. 264 y ss. Ley de Urbanismo de Aragón"),
],
}
if __name__=='__main__':
    for n,items in A.items():
        p=f'data/tema{n:02d}-visual.json'
        v=json.load(open(p,encoding='utf-8'))
        g=v.setdefault('glosario',[])
        ids={x[0] for x in g}
        for it in items:
            if it[0] not in ids: g.append(list(it)); ids.add(it[0])
        json.dump(v,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
        print(n,len(g))
